[project]
name = "10-tic-tac-toe-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "streamlit>=1.44.1",
    "streamlit-extras>=0.6.0",
]
